Update scripts/drbd to fix "no such file" bug.
LINBIT/drbd-utils pull request #38
Opened 2023-12-22 09:25 UTC by tux2bsd

Update scripts/drbd to fix "no such file" bug, which presented as below:

Starting DRBD resources:/etc/init.d/drbd: line 148: /var/lib/linstor/loop_device_mapping: No such file or directory [

2023-12-22 09:27 UTC, tux2bsd commented
Related: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1030118

2023-12-22 10:21 UTC, rck requested changes
just two smaller things that should be changed

2023-12-22 10:21 UTC, rck commented on scripts/drbd
> +		return 0
the comment is wrong here, it would be more like "nothing to do"

2023-12-22 10:21 UTC, rck commented on scripts/drbd
>  }
let's keep it. even if setup fails we "at least tried", and I'd like to keep the `0` return value

2023-12-24 08:36 UTC, tux2bsd commented
squashed locally and force pushed (to github), to make it a single commit (code the same as yesterday)

https://github.com/LINBIT/drbd-utils/pull/38/files

2023-12-27 09:11 UTC, rck approved these changes
LGTM

2023-12-27 09:11 UTC, merged